"""
dotmd-parser — aggregated dotmd-index.md tests.

When `--aggregate` is set, the parent `dotmd-index.md` discovers any
descendant `dotmd-index.md` artifacts and references them (does NOT
duplicate their `files[]` listings — that's intentional to keep the
parent token-efficient and let Claude drill down on demand).
"""
from __future__ import annotations

import io
import tempfile
import unittest
from contextlib import redirect_stdout, redirect_stderr
from pathlib import Path

from dotmd_parser.cli import run as cli_run
from dotmd_parser.index_md import (
    DEFAULT_INDEX_FILENAME,
    extract_frontmatter,
    generate_index_md,
    write_index_md,
)


def _w(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _invoke(argv: list[str]) -> tuple[int, str, str]:
    out, err = io.StringIO(), io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        try:
            cli_run(argv)
            rc = 0
        except SystemExit as e:
            rc = int(e.code) if e.code is not None else 0
    return rc, out.getvalue(), err.getvalue()


def _seed_two_children(root: Path) -> None:
    """Lay out a parent with two child folders, each pre-indexed."""
    _w(root / "README.md", "# Root\n")
    _w(root / "docs" / "SKILL.md", "# Docs\n")
    _w(root / "src" / "SKILL.md", "# Src\n")
    write_index_md(str(root / "docs"))
    write_index_md(str(root / "src"))


class TestGenerateAggregate(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        _seed_two_children(self.root)

    def tearDown(self):
        self.tmp.cleanup()

    def test_aggregate_off_by_default(self):
        md = generate_index_md(str(self.root))
        self.assertNotIn("## Sub-Indexes", md)
        fm = extract_frontmatter(md)
        self.assertNotIn("aggregates", fm)

    def test_aggregate_finds_descendant_indexes(self):
        md = generate_index_md(str(self.root), aggregate=True)
        self.assertIn("## Sub-Indexes", md)
        # Both child indexes referenced by their relative path
        self.assertIn("docs/dotmd-index.md", md)
        self.assertIn("src/dotmd-index.md", md)

    def test_aggregate_records_metadata_in_frontmatter(self):
        md = generate_index_md(str(self.root), aggregate=True)
        fm = extract_frontmatter(md)
        self.assertIn("aggregates", fm)
        agg = fm["aggregates"]
        self.assertEqual(len(agg), 2)
        paths = {a["path"] for a in agg}
        self.assertEqual(paths, {"docs/dotmd-index.md", "src/dotmd-index.md"})
        # Each entry carries content_hash + stats summary
        for entry in agg:
            self.assertIn("content_hash", entry)
            self.assertTrue(entry["content_hash"].startswith("sha256:"))
            self.assertIn("files", entry)  # stats.files

    def test_aggregate_skips_target_root_file(self):
        # Pre-create the parent's own dotmd-index.md
        write_index_md(str(self.root))
        md = generate_index_md(str(self.root), aggregate=True)
        fm = extract_frontmatter(md)
        # The parent's OWN dotmd-index.md must not appear in aggregates[].
        for entry in fm.get("aggregates", []):
            self.assertNotEqual(entry["path"], DEFAULT_INDEX_FILENAME)

    def test_aggregate_skips_user_authored_index_md(self):
        # An "alien" dotmd-index.md (not generated by dotmd-parser) must be ignored.
        _w(
            self.root / "manual" / DEFAULT_INDEX_FILENAME,
            "---\nname: hand-written\n---\n# my own\n",
        )
        md = generate_index_md(str(self.root), aggregate=True)
        fm = extract_frontmatter(md)
        for entry in fm.get("aggregates", []):
            self.assertNotIn("manual/", entry["path"])

    def test_aggregate_no_children_omits_section(self):
        with tempfile.TemporaryDirectory() as solo:
            _w(Path(solo) / "SKILL.md", "# only\n")
            md = generate_index_md(solo, aggregate=True)
            self.assertNotIn("## Sub-Indexes", md)
            fm = extract_frontmatter(md)
            self.assertEqual(fm.get("aggregates", []), [])

    def test_aggregate_chunk_marker_present(self):
        md = generate_index_md(str(self.root), aggregate=True)
        self.assertIn("<!-- chunk:sub-indexes -->", md)
        fm = extract_frontmatter(md)
        chunk_ids = [c["id"] for c in fm.get("chunks", [])]
        self.assertIn("sub-indexes", chunk_ids)


class TestCliAggregateFlag(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        _seed_two_children(self.root)

    def tearDown(self):
        self.tmp.cleanup()

    def test_aggregate_flag_writes_section(self):
        rc, _, err = _invoke(["dotmd-index", str(self.root), "--aggregate"])
        self.assertEqual(rc, 0, msg=err)
        target = self.root / DEFAULT_INDEX_FILENAME
        body = target.read_text(encoding="utf-8")
        self.assertIn("## Sub-Indexes", body)
        fm = extract_frontmatter(body)
        self.assertEqual(len(fm["aggregates"]), 2)

    def test_aggregate_flag_off_by_default_via_cli(self):
        rc, _, _ = _invoke(["dotmd-index", str(self.root)])
        self.assertEqual(rc, 0)
        target = self.root / DEFAULT_INDEX_FILENAME
        self.assertNotIn("## Sub-Indexes", target.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
